name = "Pun"
uuid = "36a8b662-68f8-55c3-b375-74bf3680e048"
authors = ["Your Name <your.email@example.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicForwardDiff = "fe4ab2f8-f6ba-4905-aa0c-1342e36db709"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
SparseArrays = "1.11.0"
Test = "1.11.0"
julia = "1.6"
